aibf/urls.py
from django.urls import path
from aibf import aibf_views
from django.contrib import admin
from django.urls import path, include
from analytic_app.views import reporte, envio_datos, envio_json, time_series

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recibir/', reporte, name='home'),  # Esto manejará la URL raíz,
    path('enviar/', envio_datos, name='envio'), 
    path('enviar2/', envio_json, name='envioJson'),  
    path("time_series/", time_series, name = 'series_tiempo'),
]



app_name='aibf'
urlpatterns = [


    


    path('',aibf_views.index,name="index"),
    path('index/',aibf_views.index,name="index"),
    path('index-2/',aibf_views.index_2,name="index-2"),
    path('market/',aibf_views.market,name="market"),
    path('coin-details/',aibf_views.coin_details,name="coin-details"),
    path('portfolio/',aibf_views.portfolio,name="portfolio"),

    path('ico-listing/',aibf_views.ico_listing,name="ico-listing"),
    path('p2p/',aibf_views.p2p,name="p2p"),
    path('future/',aibf_views.future,name="future"),
    path('trading-market/',aibf_views.trading_market,name="trading-market"),

    path('market-watch/',aibf_views.market_watch,name="market-watch"),
    path('exchange/',aibf_views.exchange,name="exchange"),
    path('banking/',aibf_views.banking,name="banking"),

    path('history/',aibf_views.history,name="history"),
    path('orders/',aibf_views.orders,name="orders"),
    path('reports/',aibf_views.reports,name="reports"),
    path('user/',aibf_views.user,name="user"),

    path('mi_perfil/',aibf_views.app_profile,name="mi_perfil"),
    path('edit-profile/',aibf_views.edit_profile,name="edit-profile"),
    path('post-details/',aibf_views.post_details,name="post-details"),
    path('perfil-compose/',aibf_views.perfil_compose,name="perfil-compose"),
    path('perfil-inbox/',aibf_views.perfil_inbox,name="perfil-inbox"),
    path('perfil-read/',aibf_views.perfil_read,name="perfil-read"),
    path('app-calender/',aibf_views.app_calender,name="app-calender"),
    path('ecom-product-grid/',aibf_views.ecom_product_grid,name="ecom-product-grid"),
    path('ecom-product-list/',aibf_views.ecom_product_list,name="ecom-product-list"),
    path('ecom-product-detail/',aibf_views.ecom_product_detail,name="ecom-product-detail"),
    path('ecom-product-order/',aibf_views.ecom_product_order,name="ecom-product-order"),
    path('ecom-checkout/',aibf_views.ecom_checkout,name="ecom-checkout"),
    path('ecom-invoice/',aibf_views.ecom_invoice,name="ecom-invoice"),
    path('ecom-customers/',aibf_views.ecom_customers,name="ecom-customers"),
    path('chart-flot/',aibf_views.chart_flot,name="chart-flot"),
    path('chart-morris/',aibf_views.chart_morris,name="chart-morris"),
    path('chart-chartjs/',aibf_views.chart_chartjs,name="chart-chartjs"),
    path('chart-chartist/',aibf_views.chart_chartist,name="chart-chartist"),
    path('chart-sparkline/',aibf_views.chart_sparkline,name="chart-sparkline"),
    path('chart-peity/',aibf_views.chart_peity,name="chart-peity"),

    path('content/',aibf_views.content,name="content"),
    path('add-content/',aibf_views.add_content,name="add-content"),
    path('menu/',aibf_views.menu,name="menu"),
    path('perfil-template/',aibf_views.perfil_template,name="perfil-template"),
    path('add-perfil/',aibf_views.add_perfil,name="add-perfil"),
    path('blog/',aibf_views.blog,name="blog"),
    path('add-blog/',aibf_views.add_blog,name="add-blog"),
    path('blog-category/',aibf_views.blog_category,name="blog-category"),

    path('ui-accordion/',aibf_views.ui_accordion,name="ui-accordion"),
    path('ui-alert/',aibf_views.ui_alert,name="ui-alert"),
    path('ui-badge/',aibf_views.ui_badge,name="ui-badge"),
    path('ui-button/',aibf_views.ui_button,name="ui-button"),
    path('ui-modal/',aibf_views.ui_modal,name="ui-modal"),
    path('ui-button-group/',aibf_views.ui_button_group,name="ui-button-group"),
    path('ui-list-group/',aibf_views.ui_list_group,name="ui-list-group"),
    path('ui-card/',aibf_views.ui_card,name="ui-card"),
    path('ui-carousel/',aibf_views.ui_carousel,name="ui-carousel"),
    path('ui-dropdown/',aibf_views.ui_dropdown,name="ui-dropdown"),
    path('ui-popover/',aibf_views.ui_popover,name="ui-popover"),
    path('ui-progressbar/',aibf_views.ui_progressbar,name="ui-progressbar"),
    path('ui-tab/',aibf_views.ui_tab,name="ui-tab"),
    path('ui-typography/',aibf_views.ui_typography,name="ui-typography"),
    path('ui-pagination/',aibf_views.ui_pagination,name="ui-pagination"),
    path('ui-grid/',aibf_views.ui_grid,name="ui-grid"),
    

    path('uc-select2/',aibf_views.uc_select2,name="uc-select2"),
    path('uc-nestable/',aibf_views.uc_nestable,name="uc-nestable"),
    path('uc-noui-slider/',aibf_views.uc_noui_slider,name="uc-noui-slider"),
    path('uc-sweetalert/',aibf_views.uc_sweetalert,name="uc-sweetalert"),
    path('uc-toastr/',aibf_views.uc_toastr,name="uc-toastr"),
    path('map-jqvmap/',aibf_views.map_jqvmap,name="map-jqvmap"),
    path('uc-lightgallery/',aibf_views.uc_lightgallery,name="uc-lightgallery"),

    path('widget-basic/',aibf_views.widget_basic,name="widget-basic"),

    path('form-element/',aibf_views.form_element,name="form-element"),
    path('form-wizard/',aibf_views.form_wizard,name="form-wizard"),
    path('form-editor/',aibf_views.form_editor,name="form-editor"),
    path('form-pickers/',aibf_views.form_pickers,name="form-pickers"),
    path('form-validation/',aibf_views.form_validation,name="form-validation"),

    path('table-bootstrap-basic/',aibf_views.table_bootstrap_basic,name="table-bootstrap-basic"),
    path('table-datatable-basic/',aibf_views.table_datatable_basic,name="table-datatable-basic"),


    path('page-login/',aibf_views.page_login,name="page-login"),
    path('page-register/',aibf_views.page_register,name="page-register"),
    path('page-forgot-password/',aibf_views.page_forgot_password,name="page-forgot-password"),
    path('page-lock-screen/',aibf_views.page_lock_screen,name="page-lock-screen"),
    path('page-empty/',aibf_views.page_empty,name="page-empty"),
    path('page-error-400/',aibf_views.page_error_400,name="page-error-400"),
    path('page-error-403/',aibf_views.page_error_403,name="page-error-403"),
    path('page-error-404/',aibf_views.page_error_404,name="page-error-404"),
    path('page-error-500/',aibf_views.page_error_500,name="page-error-500"),
    path('page-error-503/',aibf_views.page_error_503,name="page-error-503"),
    
    #Nuevos de antonio
    path('trend/',aibf_views.trend, name="trend"),
    path('seasonal/',aibf_views.seasonal, name="seasonal"),
    path('sarimax_arima/',aibf_views.sarimax_arima, name="sarimax_arima"),
    path('residuos/',aibf_views.residuos, name="residuos"),
    path('prueba_adf/',aibf_views.prueba_adf, name="prueba_adf"),
    path('prevision/',aibf_views.prevision, name="prevision"),
    path('autocorrelacion/',aibf_views.autocorrelacion, name="autocorrelacion"),
    path('random_forest/',aibf_views.random_forest, name="random_forest"),
    path('matriz_confusion/',aibf_views.matriz_confusion, name="matriz_confusion"),
    path('lead_source/',aibf_views.lead_source, name="lead_source"),
    path('last_activity/',aibf_views.last_activity, name="last_activity"),
    path('histograma/',aibf_views.histograma, name="histograma"),
    path('grafico_caja/',aibf_views.grafico_caja, name="grafico_caja"),
    path('distribucion_lead/',aibf_views.distribucion_lead, name="distribucion_lead"),
    path('curva_roc/',aibf_views.curva_roc, name="curva_roc"),
    path('count/',aibf_views.count, name="count"),
    path('costos_beneficios/',aibf_views.costos_beneficios,name="costos_beneficios"),
    path('arboles_decision/',aibf_views.arboles_decision, name="arboles_decision"),
 
    
]

    

dashboard/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('aibf.urls', namespace='aibf')),
]

aibf/models.py
from django.db import models

# Create your models here.

aibf/views.py
from django.shortcuts import render

# Create your views here.

templates/aibf/bootstrap/ui-popover.html
{% extends 'aibf/elements/layouts/admin.html' %}
{% load static %}
        
{% block additional_css %}
{% endblock %}
        
{% block content %}
<!--**********************************
	Content body start
***********************************-->
<div class="content-body">
	<div class="container-fluid">
		<!-- row -->

		<div class="row">
			<div class="col-12">
				<div class="card">
					<div class="card-header">
						<h4 class="card-title">Bootstrap popover</h4>
					</div>
					<div class="card-body">

						<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Magnam laborum dolorum culpa a maiores officia ab. Cumque necessitatibus voluptates soluta, ullam numquam nulla. Et a architecto veritatis sint, autem cupiditate
							iure illo pariatur eum, praesentium numquam ea quaerat ipsam? Corrupti nobis illo itaque quae, qui numquam vero ipsa, reiciendis sit repudiandae molestiae natus vel voluptatibus exercitationem ducimus neque harum ad,
							commodi excepturi repellat eos fugiat minus eius. Doloremque itaque repudiandae saepe quia temporibus? Vitae, reprehenderit aliquam facilis qui at quis provident in maiores illo laborum, voluptatem recusandae cupiditate
							nemo. Nulla iusto ad consequatur reprehenderit quod accusamus, vitae, blanditiis quae ut tenetur nobis animi dolorum consectetur dignissimos amet illo provident nam obcaecati eligendi molestias tempora? Ad nam nobis
							eaque consequatur tempore tenetur eius ipsum reprehenderit dignissimos inventore. Id recusandae nemo dicta rerum. Distinctio itaque, veniam dolore inventore aliquid assumenda neque. Deserunt!
						</p>
						<div class="bootstrap-popover-wrapper">
							<div class="bootstrap-popover d-inline-block">
								<button type="button" class="btn btn-primary btn-sm px-4 " data-bs-container="body" data-bs-toggle="popover" data-bs-placement="left" data-bs-content="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor." title="Popover in Left">Left</button>
							</div>
							<div class="bootstrap-popover d-inline-block">
								<button type="button" class="btn btn-primary btn-sm px-4 " data-bs-container="body" data-bs-toggle="popover" data-bs-placement="top" data-bs-content="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor." title="Popover in Right">Top</button>
							</div>
							<div class="bootstrap-popover d-inline-block">
								<button type="button" class="btn btn-primary btn-sm px-4 " data-bs-container="body" data-bs-toggle="popover" data-bs-placement="bottom" data-bs-content="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor." title="Popover in Bottom">Bottom</button>
							</div>
							<div class="bootstrap-popover d-inline-block">
								<button type="button" class="btn btn-primary btn-sm px-4 " data-bs-container="body" data-bs-toggle="popover" data-bs-placement="right" data-bs-content="Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor." title="Popover in Right">Right</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!--**********************************
	Content body end
***********************************-->
{% endblock %}

templates/aibf/elements/chat-box.html
<!--ESTÁ LISTO, SOLO FALTA AÑADIR LO QUE QUERAMOS-->
<!--ESTO ES EL MAIL QUE APARECE EN EL MENÚ-->

{% load static %}
<div class="chatbox">
	<div class="chatbox-close"></div>
	<div class="custom-tab-1">
		<ul class="nav nav-tabs">
			<li class="nav-item">
				<a class="nav-link" data-bs-toggle="tab" href="#notes">NOTIFICACIONES</a>
			</li>
			<!--li class="nav-item">
				<a class="nav-link" data-bs-toggle="tab" href="#alerts">Alerts</a>
			</li>
			<li class="nav-item">
				<a class="nav-link active" data-bs-toggle="tab" href="#chat">Chat</a>
			</li-->
		</ul>
		<div class="tab-content">
			<div class="tab-pane fade active show" id="chat" role="tabpanel">
				<div class="card mb-sm-3 mb-md-0 contacts_card dlab-chat-user-box">
					
					<div class="card-body contacts_body p-0 dlab-scroll  " id="DLAB_W_Contacts_Body">
						<!--AQUI VA EL BUCLE DE LAS NOTIFICACIONES QUE LE ENVIAMOS-->
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

templates/aibf/elements/footer.html
{% load static %}
<div class="footer">
    <div class="copyright">
        <p>Copyright © Designed &amp; Developed by PrácticasAIBF"
                target="_blank">DexignLab</a> <span class="current-year">2024</span>
        </p>
    </div>
</div>

templates/aibf/pages/page-forgot-password.html
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
	{% load static custom_tags %}
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="keywords" content="" />
	<meta name="author" content="DexignLab" />
	<meta name="robots" content="" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="{{ dz_array.public.description }}" />
	<meta property="og:title" content="{{ dz_array.public.og_title }}" />
	<meta property="og:description" content="{{ dz_array.public.og_description }}" />
	<meta property="og:image" content="{{ dz_array.public.og_image }}" />
	<meta name="format-detection" content="telephone=no">


	<!-- PAGE TITLE HERE -->
	<title>{{ dz_array.public.title }}</title>
	
	<!-- FAVICONS ICON -->
	<link rel="shortcut icon" type="image/png" href="{% static dz_array.public.favicon  %}" />
	{% for cssurl in dz_array.pagelevel.aibf.aibf_views.css|getdata:request.path %}
	<link rel="stylesheet" href="{% static cssurl %}" >
	{% endfor %}
	{% for cssurl in dz_array.global.css %}
	<link rel="stylesheet" href="{% static cssurl %}">
	{% endfor %}
	{% block additional_css %}
	{% endblock %}
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0">
	
</head>

<body class="body  h-100">
	<div class="authincation d-flex flex-column flex-lg-row flex-column-fluid">
		<div class="login-aside text-center  d-flex flex-column flex-row-auto">
			<div class="d-flex flex-column-auto flex-column pt-lg-40 pt-15">
				<div class="text-center mb-lg-4 mb-2 pt-5 logo">
					<img src="{% static 'aibf/images/logo-white.png' %}" alt="">
				</div>
				<h3 class="mb-2 text-white">¡Bienvenido!</h3>
				<p class="mb-4">El Forecast No Habia Estado Mas Al Alcance</p>
			</div>
			<div class="aside-image position-relative" style="background-image:url({% static 'aibf/images/background/pic-2.png' %});">
				<img class="img1 move-1" src="{% static 'aibf/images/background/pic3.png' %}" alt="">
				<img class="img2 move-2" src="{% static 'aibf/images/background/pic4.png' %}" alt="">
				<img class="img3 move-3" src="{% static 'aibf/images/background/pic5.png' %}" alt="">
				
			</div>
		</div>
		<div class="container flex-row-fluid d-flex flex-column justify-content-center position-relative overflow-hidden p-7 mx-auto">
			<div class="d-flex justify-content-center h-100 align-items-center">
				<div class="authincation-content style-2">
					<div class="row no-gutters">
						<div class="col-xl-12 tab-content">
							<div id="sign-up" class="auth-form tab-pane fade show active  form-validation">
								<form action="{% url 'aibf:index' %}">
									<div class="text-center mb-4">
										<h3 class="text-center mb-2 text-dark">Olvidaste La Contraseña</h3>
										<span>Tus Predicciones</span>
									</div>
									<div class="row mb-4">
										<div class="col-xl-6 col-12"><!--
											<a href="javascript:void(0);" class="btn btn-outline-dark btn-sm btn-block">
											<svg class="me-1" width="16" height="16" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
											<path d="M27.9851 14.2618C27.9851 13.1146 27.8899 12.2775 27.6837 11.4094H14.2788V16.5871H22.1472C21.9886 17.8738 21.132 19.8116 19.2283 21.1137L19.2016 21.287L23.44 24.4956L23.7336 24.5242C26.4304 22.0904 27.9851 18.5093 27.9851 14.2618Z" fill="#4285F4"/>
											<path d="M14.279 27.904C18.1338 27.904 21.37 26.6637 23.7338 24.5245L19.2285 21.114C18.0228 21.9356 16.4047 22.5092 14.279 22.5092C10.5034 22.5092 7.29894 20.0754 6.15663 16.7114L5.9892 16.7253L1.58205 20.0583L1.52441 20.2149C3.87224 24.7725 8.69486 27.904 14.279 27.904Z" fill="#34A853"/>
											<path d="M6.15656 16.7113C5.85516 15.8432 5.68072 14.913 5.68072 13.9519C5.68072 12.9907 5.85516 12.0606 6.14071 11.1925L6.13272 11.0076L1.67035 7.62109L1.52435 7.68896C0.556704 9.58024 0.00146484 11.7041 0.00146484 13.9519C0.00146484 16.1997 0.556704 18.3234 1.52435 20.2147L6.15656 16.7113Z" fill="#FBBC05"/>
											<path d="M14.279 5.3947C16.9599 5.3947 18.7683 6.52635 19.7995 7.47204L23.8289 3.6275C21.3542 1.37969 18.1338 0 14.279 0C8.69485 0 3.87223 3.1314 1.52441 7.68899L6.14077 11.1925C7.29893 7.82856 10.5034 5.3947 14.279 5.3947Z" fill="#EB4335"/>
											</svg>

											Sign in with Google</a>-->
										</div>
										<div class="col-xl-6 col-12"><!--
											<a href="javascript:void(0);" class="btn btn-outline-dark btn-sm btn-block mt-xl-0 mt-3">
											<svg class="me-1" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 456.008 560.035"><path d="M380.844 297.529c.787 84.752 74.349 112.955 75.164 113.314-.622 1.988-11.754 40.191-38.756 79.652-23.343 34.117-47.568 68.107-85.731 68.811-37.499.691-49.557-22.236-92.429-22.236-42.859 0-56.256 21.533-91.753 22.928-36.837 1.395-64.889-36.891-88.424-70.883-48.093-69.53-84.846-196.475-35.496-282.165 24.516-42.554 68.328-69.501 115.882-70.192 36.173-.69 70.315 24.336 92.429 24.336 22.1 0 63.59-30.096 107.208-25.676 18.26.76 69.517 7.376 102.429 55.552-2.652 1.644-61.159 35.704-60.523 106.559M310.369 89.418C329.926 65.745 343.089 32.79 339.498 0 311.308 1.133 277.22 18.785 257 42.445c-18.121 20.952-33.991 54.487-29.709 86.628 31.421 2.431 63.52-15.967 83.078-39.655"/></svg>
											Sign in with Apple</a>-->
										</div>
									</div>
									<div class="sepertor">
										<span class="d-block mb-4 fs-13">Con el perfil</span>
									</div>
									<div class="mb-3">
										<label for="exampleFormControlInput1" class="form-label required">Direccion De Correo</label>
									  <input type="perfil" class="form-control" id="exampleFormControlInput1" value="hello@example.com">
									</div>
									
									<div class="form-row d-flex justify-content-between mt-4 mb-2">
										<div class="mb-3">
											<div class="form-check custom-checkbox mb-0">
												<input type="checkbox" class="form-check-input" id="customCheckBox1" required="">
												<label class="form-check-label" for="customCheckBox1">¿Ya Tienes Cuenta?</label>
											</div>
										</div>
										<div class="mb-4">
											<a href="{% url 'aibf:page-forgot-password' %}" class="btn-link text-primary">¿Necesitas Ayuda?</a>
										</div>
									</div>
									<button type="submit" class="btn btn-block btn-primary">ACCEDER</button>
									
								</form>
								<div class="new-account mt-3 text-center">
									<p class="font-w500">Already have an account? <a class="text-primary" href="{% url 'aibf:page-login' %}" data-toggle="tab">Registrate</a></p>
								</div>
							</div>
								<div class="d-flex align-items-center justify-content-center">
									<a href="javascript:void(0);" class="text-primary">Termins</a>
									<a href="javascript:void(0);" class="text-primary mx-5">Planes</a>
									<a href="javascript:void(0);" class="text-primary">Contactanos</a>
								</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>


<!--**********************************
	Scripts
***********************************-->
<!-- Required vendors -->
{% for jsurl in dz_array.global.js.top %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% for jsurl in dz_array.pagelevel.aibf.aibf_views.js|getdata:request.path %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% for jsurl in dz_array.global.js.bottom %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% block additional_js %}
{% endblock %}
</body>
</html>

templates/aibf/pages/page-login.html
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
	{% load static custom_tags %}
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="keywords" content="" />
	<meta name="author" content="DexignLab" />
	<meta name="robots" content="" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="{{ dz_array.public.description }}" />
	<meta property="og:title" content="{{ dz_array.public.og_title }}" />
	<meta property="og:description" content="{{ dz_array.public.og_description }}" />
	<meta property="og:image" content="{{ dz_array.public.og_image }}" />
	<meta name="format-detection" content="telephone=no">


	<!-- PAGE TITLE HERE -->
	<title>{{ dz_array.public.title }}</title>
	
	<!-- FAVICONS ICON -->
	<link rel="shortcut icon" type="image/png" href="{% static dz_array.public.favicon  %}" />
	{% for cssurl in dz_array.pagelevel.aibf.aibf_views.css|getdata:request.path %}
	<link rel="stylesheet" href="{% static cssurl %}" >
	{% endfor %}
	{% for cssurl in dz_array.global.css %}
	<link rel="stylesheet" href="{% static cssurl %}">
	{% endfor %}
	{% block additional_css %}
	{% endblock %}

	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0">
	
</head>

<body class="body">
	<div class="authincation d-flex flex-column flex-lg-row flex-column-fluid">
		<div class="login-aside text-center  d-flex flex-column flex-row-auto">
			<div class="d-flex flex-column-auto flex-column pt-lg-40 pt-15">
				<div class="text-center mb-lg-4 mb-2 pt-5 logo">
					<img src="{% static 'logo.png' %}" alt="">
				</div>
				<h3 class="mb-2 text-white">¡Bienvenido!</h3>
				<p class="mb-4">El Forecast No Habia Estado Más Al Alcance</p>
			</div>
			<div class="aside-image position-relative" aling="image-center" style="background-image:url('{% static 'fondo.png' %}')">
				<img class="img1 move-1" src="" alt="">
				<img class="img2 move-2" src="" alt="">
				<img class="img3 move-3" src="" alt="">
				
			</div>
		</div>
		<div class="container flex-row-fluid d-flex flex-column justify-content-center position-relative overflow-hidden p-7 mx-auto">
			<div class="d-flex justify-content-center h-100 align-items-center">
				<div class="authincation-content style-2">
					<div class="row no-gutters">
						<div class="col-xl-12 tab-content">
							<div id="sign-up" class="auth-form tab-pane fade show active  form-validation">
								<form action="{% url 'aibf:index' %}">
									<div class="text-center mb-4">
										<h3 class="text-center mb-2 text-dark">Registrate</h3>
										<span>Nuestras Predicciones</span>
									</div>
									
									<div class="sepertor">
										<span class="d-block mb-4 fs-13">Con el perfil</span>
									</div>
									<div class="mb-3">
										<label for="exampleFormControlInput1" class="form-label required">Direccion Correo</label>
									  <input type="perfil" class="form-control" id="exampleFormControlInput1" value="hello@example.com">
									</div>
									<div class="mb-3 position-relative">
										<label class="form-label required">Contraseña</label>
										<input type="password" id="dlab-password" class="form-control" value="123456">
										<span class="show-pass eye">
											<i class="fa fa-eye-slash"></i>
											<i class="fa fa-eye"></i>
										
										</span>
									</div>
									<div class="form-row d-flex justify-content-between mt-4 mb-2">
										<div class="mb-3">
											<div class="form-check custom-checkbox mb-0">
												<input type="checkbox" class="form-check-input" id="customCheckBox1" required="">
												<label class="form-check-label" for="customCheckBox1">Recordar</label>
											</div>
										</div>
										<div class="mb-4">
											<a href="{% url 'aibf:page-forgot-password' %}" class="btn-link text-primary">¿Has Olvidado La Contraseña?</a>
										</div>
									</div>
									<button class="btn btn-block btn-primary">Registrate</button>
									
								</form>
								<div class="new-account mt-3 text-center">
									<p class="font-w500">¿Tienes Cuenta? <a class="text-primary" href="{% url 'aibf:page-login' %}" data-toggle="tab">Registrate</a></p>
								</div>
							</div>
								<div class="d-flex align-items-center justify-content-center">
									<a href="javascript:void(0);" class="text-primary">Terminos</a>
									<a href="javascript:void(0);" class="text-primary mx-5">Planes</a>
									<a href="javascript:void(0);" class="text-primary">Contacta</a>
								</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

<!--**********************************
	Scripts
***********************************-->
<!-- Required vendors -->
{% for jsurl in dz_array.global.js.top %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% for jsurl in dz_array.pagelevel.aibf.aibf_views.js|getdata:request.path %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% for jsurl in dz_array.global.js.bottom %}
<script src="{% static jsurl %}"></script>
{% endfor %}

{% block additional_js %}
{% endblock %}
</body>
</html>